### ISSUE TITLE
ne prikaže željenih podatkov

### ISSUE THREAD

**Issue by rozmanU14** [jaanos/APPR-2015-16#6]
podatke novipodatkiDRZAVE mi je že pokazalo v željeni obliki, to kodo sem shranila, zdaj pa mi za isto kodo vrača napako "Error in matrix(., ncol = 1) : 
  'data' must be of a vector type, was 'NULL' "

**Comment by jaanos** [comment]
Tale issue je šel na napačno mesto (naj moj repozitorij namesto tvojega), tako da ga tukaj zapiram.

Problem je sicer v odvečnem prelomu vrstice, kot sem ti napisal v komentarju na commit rozmanU14@c8088ea3a0a07b797a694edb6ae2e68c5ffd5ed3.
