### ISSUE TITLE
tabela in primerjava podatkov

### ISSUE THREAD

**Issue by LonjaTT** [jaanos/APPR-2015-16#9]
S spletne strani:http://www.egmus.eu/nc/en/statistics/complete_data/
bi rada vzela tabelo za podatke muzejev v evropskih državah, ampak potrebujem samo določene podatke. Na koncu bi rada naredila primerjavo med Evropo in Slovenijo.

**Comment by jaanos** [comment]
Podatke lahko dobiš npr. tako:

``` R
library(rvest)
stran <- html_session("http://www.egmus.eu/nc/en/statistics/complete_data/") %>%
  read_html()
tabela <- stran %>% html_node(xpath = "//table[@class='statistiktab']") %>%
  html_table()
```

Podatke bo treba seveda počistiti in jih pretvoriti v števila ter izbrati želene. Potem lahko seveda narediš želene primerjave.

**Comment by jaanos** [comment]
Vidim, da je to šlo na napačno mesto, tako da zapiram.
